### ISSUE TITLE
CSS instead of Theme-UI?

### ISSUE THREAD

**Issue by allanjsx** [spacecakes/react-smooth-carousel#8]
Thank you for creating such a performant swiper. It looks like using `theme-ui` could introduce additional dependencies. Is it possible to refactor this to use pure css styles? Thank you!

**Comment by spacecakes** [comment]
Hello! Really sorry for the late reply. You're right it uses `theme-ui` as that was what I was working mostly with at the time, but the CSS is actually very simple and could be ripped out and put into whatever CSS-in-JS lib you want, or just plain inline styles if you prefer. 

I was never able to finish this project, but the general concept and implementation is still relevant and could hopefully be useful to someone looking for a carousel without ugly JS scroll hijacking and other quirks. You'd just have to copy the code and use it directly in your app. Also see readme about known issues. Sorry about that.
